### ISSUE TITLE
Visualização de Informações do Usuário (Perfil)

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#55]
## Descreva a solução ou solicitação de recurso ideal
Visualização dos dados inerentes ao usuário selecionado a partir de uma lista ou menu de acesso.

## Dificuldade, impacto e pontuação de uso
| Dificuldade técnica | Objetivos do usuário | Frequência de uso |
| -------------------- | -------------------- | -------------------- |
| Médio | Administrador executar CRUD nos usuários | Semanalmente |

## Como isso se vincula ao nosso produto atual?
Funcionalidade necessária para visualização de dados inerentes aos usuários da plataforma. [Variável]

## Quem requisitou isso?
Product Manager

## Design

![image.png](https://images.zenhubusercontent.com/5e9a31126a44049a3a9b9e85/cb0ab0f0-38dc-4f2f-8df9-668915a4939d)

Nota: Este Perfil tende mais a ser de algum profissional de saúde [Médico Patologista] que normalmente atende dentro do Laboratório, ele pode ser dono, colaborador ou terceiro. Os Três boxes ao lado dos dados Básicos podem servir para mostrar dados de diferentes indicadores conforme cada perfil de usuário.

Figma: https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=294%3A735

## Definição de Feito [DoD]
*Definition of Done:* Descreva abaixo detalhadamente todos os requisitos necessários para que essa Issue seja considerada como **DONE**.

As informações devem estar de acordo com o Layout.

- [x] Criar Issue 
- [x] Design/Layout
- [x] Criar novo Branch e Pull-request para essa issue
- [x] Criar um template o mais fiel possível ao Design com o Vuetify
- [ ] Implementar as funcionalidades da view/componente e outras camadas de serviço
- [ ] Review do código [Frontend/Backend]
- [ ] Review do Design e UI/UX
- [ ] Liberar Issue para merge

## API
Issue - https://github.com/Hubvet8/hubvet-api/issues/45
Docs - https://dev.hubvet.app/docs#usuario-usuarios

**Comment by johhny0** [comment]
@PCiranda Conforme conversamos segue os campos que estão faltando:

- Tipo de usuario
- Email
- Ultima atividades
- Conta ativa
- Conta verificada
- link de indicação
- Bio
- Genero
- Telefones

A questão do telefone não sei se eu não soube como pegar usando o framework VueApiQuery ou se ainda não foi implementado
