### ISSUE TITLE
Perfil da Organização

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#63]
## Descreva a solução ou solicitação de recurso ideal
Visualização e Edição do Perfil da Organização na Plataforma.

## Dificuldade, impacto e pontuação de uso
| Dificuldade técnica | Objetivos do usuário | Frequência de uso |
| -------------------- | -------------------- | -------------------- |
| Baixa | Configurar e Visualizar informações da empresa | esporadicamente |

## Como isso se vincula ao nosso produto atual?
Necessário para organizarmos as informações das empresas na Plataforma.

## Quem requisitou isso?
Product Manager

## Design

- [x] Visualização do Perfil da Organização 
https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=511%3A62
- [ ] Edição das informação da Organização
https://www.figma.com/file/UXDidWh92NmqWX8RFTzHZb/ERP-Hubvet-UI?node-id=512%3A0
Nota: Para edição da organização igual foi feito do usuário [#50] preciso rever o conceito com o @PCiranda (Parei na tela de "Outras Informções")

## Definição de Feito [DoD]
*Definition of Done:* Descreva abaixo detalhadamente todos os requisitos necessários para que essa Issue seja considerada como **DONE**.

- [x] Criar Issue
- [ ] Design/Layout
- [ ] Criar novo Branch e Pull-request para essa issue
- [ ] Criar um template o mais fiel possível ao Design com o Vuetify
- [ ] Implementar as funcionalidades da view/componente e outras camadas de serviço
- [ ] Review do código [Frontend/Backend]
- [ ] Review do Design e UI/UX
- [ ] Liberar Issue para merge

**Comment by PCiranda** [comment]
### API
Issue - Hubvet8/hubvet-api#46
Docs - https://dev.hubvet.app/docs#organizacoes-organizacoes
