### ISSUE TITLE
Template para a aplicação frontend

### ISSUE THREAD

**Issue by leolands** [Hubvet8/hubvet-web#7]
Em pesquisa achei interessante este template da www.pixinvent.com que é feito em Vue + Laravel.

Template Demo-1: https://pixinvent.com/demo/vuexy-vuejs-laravel-admin-template/demo-1/dashboard/analytics

Outros tipos: https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/landing/

**Comment by leolands** [comment]
@PCiranda vamos trabalhar basicamente Material.io pras telas de design e Vuetify como framework. Correto?

**Comment by PCiranda** [comment]
Sim, correto.
